### ISSUE TITLE
compile error: AsyncAPDS9306::begin is redefining default value in .cpp and .h

### ISSUE THREAD

**Issue by limetronics** [gmarti/AsyncAPDS9306#1]
Code doesn't compile because the default parameter is defined in both .cpp and .h file.

Fix: remove the redefinition in AsyncAPDS9306.cpp

line 66:
bool AsyncAPDS9306::begin(APDS9306_ALS_GAIN_t again, APDS9306_ALS_MEAS_RES_t atime) {
line 156:
int AsyncAPDS9306::_write(uint8_t reg, bool i2cStopMessage) {
line 162:
int AsyncAPDS9306::_writeValue(uint8_t reg, uint8_t value, bool i2cStopMessage) {

Code now compiles fine!

**Comment by gmarti** [comment]
Oh, sorry i didn't see you posted an issue 2 years ago 
I didn't get any notifications from github and thought the project was uninteresting :p

I'll accept the pull request soon, thanks
